package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.AttendActivityExample;
import com.example.studentsystem.entity.AttendActivityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int countByExample(AttendActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByExample(AttendActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByPrimaryKey(AttendActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insert(AttendActivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insertSelective(AttendActivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    List<AttendActivityKey> selectByExample(AttendActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExampleSelective(@Param("record") AttendActivityKey record, @Param("example") AttendActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExample(@Param("record") AttendActivityKey record, @Param("example") AttendActivityExample example);
}