package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.NewsLetter;
import com.example.studentsystem.entity.NewsLetterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsLetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int countByExample(NewsLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByExample(NewsLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByPrimaryKey(Integer newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insert(NewsLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insertSelective(NewsLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    List<NewsLetter> selectByExample(NewsLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    NewsLetter selectByPrimaryKey(Integer newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExampleSelective(@Param("record") NewsLetter record, @Param("example") NewsLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExample(@Param("record") NewsLetter record, @Param("example") NewsLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByPrimaryKeySelective(NewsLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByPrimaryKey(NewsLetter record);
}