package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.Newsletter;
import com.example.studentsystem.entity.NewsletterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsletterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int countByExample(NewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int deleteByExample(NewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int deleteByPrimaryKey(Integer newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int insert(Newsletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int insertSelective(Newsletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    List<Newsletter> selectByExample(NewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    Newsletter selectByPrimaryKey(Integer newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int updateByExampleSelective(@Param("record") Newsletter record, @Param("example") NewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int updateByExample(@Param("record") Newsletter record, @Param("example") NewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int updateByPrimaryKeySelective(Newsletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    int updateByPrimaryKey(Newsletter record);
}