package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.SchoolActivity;
import com.example.studentsystem.entity.SchoolActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int countByExample(SchoolActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int deleteByExample(SchoolActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int insert(SchoolActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int insertSelective(SchoolActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    List<SchoolActivity> selectByExample(SchoolActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    SchoolActivity selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByExampleSelective(@Param("record") SchoolActivity record, @Param("example") SchoolActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByExample(@Param("record") SchoolActivity record, @Param("example") SchoolActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByPrimaryKeySelective(SchoolActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolactivity
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByPrimaryKey(SchoolActivity record);
}