package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.SelectedCourse;
import com.example.studentsystem.entity.SelectedCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectedCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int countByExample(SelectedCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int deleteByExample(SelectedCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int insert(SelectedCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int insertSelective(SelectedCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    List<SelectedCourse> selectByExample(SelectedCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByExampleSelective(@Param("record") SelectedCourse record, @Param("example") SelectedCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    int updateByExample(@Param("record") SelectedCourse record, @Param("example") SelectedCourseExample example);
}