package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.SubscribeNewsExample;
import com.example.studentsystem.entity.SubscribeNewsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubscribeNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int countByExample(SubscribeNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByExample(SubscribeNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int deleteByPrimaryKey(SubscribeNewsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insert(SubscribeNewsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int insertSelective(SubscribeNewsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    List<SubscribeNewsKey> selectByExample(SubscribeNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExampleSelective(@Param("record") SubscribeNewsKey record, @Param("example") SubscribeNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribenews
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    int updateByExample(@Param("record") SubscribeNewsKey record, @Param("example") SubscribeNewsExample example);
}