package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.SubscribedSubject;
import com.example.studentsystem.entity.SubscribedSubjectExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SubscribedSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int countByExample(SubscribedSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int deleteByExample(SubscribedSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int insert(SubscribedSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int insertSelective(SubscribedSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    List<SubscribedSubject> selectByExample(SubscribedSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int updateByExampleSelective(@Param("record") SubscribedSubject record, @Param("example") SubscribedSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribedsubject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    int updateByExample(@Param("record") SubscribedSubject record, @Param("example") SubscribedSubjectExample example);
}