package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.SubscribedNewsletterExample;
import com.example.studentsystem.entity.SubscribedNewsletterKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SubscribedNewsletterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int countByExample(SubscribedNewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int deleteByExample(SubscribedNewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int deleteByPrimaryKey(SubscribedNewsletterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int insert(SubscribedNewsletterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int insertSelective(SubscribedNewsletterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    List<SubscribedNewsletterKey> selectByExample(SubscribedNewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int updateByExampleSelective(@Param("record") SubscribedNewsletterKey record, @Param("example") SubscribedNewsletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribednewsletter
     *
     * @mbggenerated Thu Apr 28 23:25:59 BST 2022
     */
    int updateByExample(@Param("record") SubscribedNewsletterKey record, @Param("example") SubscribedNewsletterExample example);
}