package com.example.studentsystem.mapper;

import com.example.studentsystem.entity.TestTable;
import com.example.studentsystem.entity.TestTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int countByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int deleteByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int deleteByPrimaryKey(Integer testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int insert(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int insertSelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    List<TestTable> selectByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    TestTable selectByPrimaryKey(Integer testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int updateByExampleSelective(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int updateByExample(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int updateByPrimaryKeySelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testTable
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    int updateByPrimaryKey(TestTable record);
}