package com.example.studentsystem.pattern.composite;

import com.example.studentsystem.entity.Event;

import java.util.Date;

public class SchoolActivityEvent extends Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String activityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityDescription
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String activitydescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityStart
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Date activitystart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityEnd
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Date activityend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolactivity.activityDay
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer activityday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityID
     *
     * @return the value of schoolactivity.activityID
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityID
     *
     * @param activityid the value for schoolactivity.activityID
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityName
     *
     * @return the value of schoolactivity.activityName
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityName
     *
     * @param activityname the value for schoolactivity.activityName
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityDescription
     *
     * @return the value of schoolactivity.activityDescription
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getActivitydescription() {
        return activitydescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityDescription
     *
     * @param activitydescription the value for schoolactivity.activityDescription
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivitydescription(String activitydescription) {
        this.activitydescription = activitydescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityStart
     *
     * @return the value of schoolactivity.activityStart
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Date getActivitystart() {
        return activitystart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityStart
     *
     * @param activitystart the value for schoolactivity.activityStart
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivitystart(Date activitystart) {
        this.activitystart = activitystart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityEnd
     *
     * @return the value of schoolactivity.activityEnd
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Date getActivityend() {
        return activityend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityEnd
     *
     * @param activityend the value for schoolactivity.activityEnd
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivityend(Date activityend) {
        this.activityend = activityend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolactivity.activityDay
     *
     * @return the value of schoolactivity.activityDay
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getActivityday() {
        return activityday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolactivity.activityDay
     *
     * @param activityday the value for schoolactivity.activityDay
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setActivityday(Integer activityday) {
        this.activityday = activityday;
    }

    public Event toEvent() {
        Event event = new Event();
        event.setTitle(activityname);
        event.setStart(activitystart);
        event.setEnd(activityend);
        event.setBackgroundColor(getBackgroundColor());
        event.setBorderColor(getBorderColor());
        event.setAllDay(isAllDay());
        event.setId(String.valueOf(activityid));
        return event;
    }
}