package com.example.studentsystem.entity;

public class AttendActivityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendactivity.activityID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendactivity.studentID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendactivity.activityID
     *
     * @return the value of attendactivity.activityID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendactivity.activityID
     *
     * @param activityid the value for attendactivity.activityID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendactivity.studentID
     *
     * @return the value of attendactivity.studentID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendactivity.studentID
     *
     * @param studentid the value for attendactivity.studentID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
}