package com.example.studentsystem.entity;

public class College {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer collegeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String collegename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeID
     *
     * @return the value of college.collegeID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeID
     *
     * @param collegeid the value for college.collegeID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeName
     *
     * @return the value of college.collegeName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getCollegename() {
        return collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeName
     *
     * @param collegename the value for college.collegeName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCollegename(String collegename) {
        this.collegename = collegename;
    }
}