package com.example.studentsystem.entity;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacherID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseTime
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String coursetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.classRoom
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String classroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseWeek
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer courseweek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseType
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String coursetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.majorID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer majorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseStart
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Date coursestart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseEnd
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Date courseend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseID
     *
     * @return the value of course.courseID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseID
     *
     * @param courseid the value for course.courseID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacherID
     *
     * @return the value of course.teacherID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacherID
     *
     * @param teacherid the value for course.teacherID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseTime
     *
     * @return the value of course.courseTime
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getCoursetime() {
        return coursetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseTime
     *
     * @param coursetime the value for course.courseTime
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCoursetime(String coursetime) {
        this.coursetime = coursetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.classRoom
     *
     * @return the value of course.classRoom
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.classRoom
     *
     * @param classroom the value for course.classRoom
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseWeek
     *
     * @return the value of course.courseWeek
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getCourseweek() {
        return courseweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseWeek
     *
     * @param courseweek the value for course.courseWeek
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCourseweek(Integer courseweek) {
        this.courseweek = courseweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseType
     *
     * @return the value of course.courseType
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getCoursetype() {
        return coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseType
     *
     * @param coursetype the value for course.courseType
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.majorID
     *
     * @return the value of course.majorID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getMajorid() {
        return majorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.majorID
     *
     * @param majorid the value for course.majorID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setMajorid(Integer majorid) {
        this.majorid = majorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseStart
     *
     * @return the value of course.courseStart
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Date getCoursestart() {
        return coursestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseStart
     *
     * @param coursestart the value for course.courseStart
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCoursestart(Date coursestart) {
        this.coursestart = coursestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseEnd
     *
     * @return the value of course.courseEnd
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Date getCourseend() {
        return courseend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseEnd
     *
     * @param courseend the value for course.courseEnd
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setCourseend(Date courseend) {
        this.courseend = courseend;
    }
}