package com.example.studentsystem.entity;

public class Fee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeID
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private Integer feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeAmount
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private Integer feeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feePayerUserName
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private Integer feepayerusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeStatus
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private Integer feestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeOnlineOrOffline
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private Integer feeonlineoroffline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feePaymentMethod
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    private String feepaymentmethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeID
     *
     * @return the value of fee.feeID
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public Integer getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeID
     *
     * @param feeid the value for fee.feeID
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeeid(Integer feeid) {
        this.feeid = feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeAmount
     *
     * @return the value of fee.feeAmount
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public Integer getFeeamount() {
        return feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeAmount
     *
     * @param feeamount the value for fee.feeAmount
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeeamount(Integer feeamount) {
        this.feeamount = feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feePayerUserName
     *
     * @return the value of fee.feePayerUserName
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public Integer getFeepayerusername() {
        return feepayerusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feePayerUserName
     *
     * @param feepayerusername the value for fee.feePayerUserName
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeepayerusername(Integer feepayerusername) {
        this.feepayerusername = feepayerusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeStatus
     *
     * @return the value of fee.feeStatus
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public Integer getFeestatus() {
        return feestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeStatus
     *
     * @param feestatus the value for fee.feeStatus
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeestatus(Integer feestatus) {
        this.feestatus = feestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeOnlineOrOffline
     *
     * @return the value of fee.feeOnlineOrOffline
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public Integer getFeeonlineoroffline() {
        return feeonlineoroffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeOnlineOrOffline
     *
     * @param feeonlineoroffline the value for fee.feeOnlineOrOffline
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeeonlineoroffline(Integer feeonlineoroffline) {
        this.feeonlineoroffline = feeonlineoroffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feePaymentMethod
     *
     * @return the value of fee.feePaymentMethod
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public String getFeepaymentmethod() {
        return feepaymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feePaymentMethod
     *
     * @param feepaymentmethod the value for fee.feePaymentMethod
     *
     * @mbggenerated Sun Apr 24 01:57:47 BST 2022
     */
    public void setFeepaymentmethod(String feepaymentmethod) {
        this.feepaymentmethod = feepaymentmethod;
    }
}