package com.example.studentsystem.entity;

public class Fee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeAmount
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer feeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feePayerUserName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String feepayerusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.feeStatus
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer feestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeID
     *
     * @return the value of fee.feeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeID
     *
     * @param feeid the value for fee.feeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setFeeid(Integer feeid) {
        this.feeid = feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeAmount
     *
     * @return the value of fee.feeAmount
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getFeeamount() {
        return feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeAmount
     *
     * @param feeamount the value for fee.feeAmount
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setFeeamount(Integer feeamount) {
        this.feeamount = feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feePayerUserName
     *
     * @return the value of fee.feePayerUserName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getFeepayerusername() {
        return feepayerusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feePayerUserName
     *
     * @param feepayerusername the value for fee.feePayerUserName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setFeepayerusername(String feepayerusername) {
        this.feepayerusername = feepayerusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.feeStatus
     *
     * @return the value of fee.feeStatus
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getFeestatus() {
        return feestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.feeStatus
     *
     * @param feestatus the value for fee.feeStatus
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setFeestatus(Integer feestatus) {
        this.feestatus = feestatus;
    }
}