package com.example.studentsystem.entity;

import java.util.Date;

public class NewsLetter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String newsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsMessage
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String newsmessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.publishTime
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Date publishtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsID
     *
     * @return the value of newsletter.newsID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsID
     *
     * @param newsid the value for newsletter.newsID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsName
     *
     * @return the value of newsletter.newsName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getNewsname() {
        return newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsName
     *
     * @param newsname the value for newsletter.newsName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setNewsname(String newsname) {
        this.newsname = newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsMessage
     *
     * @return the value of newsletter.newsMessage
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getNewsmessage() {
        return newsmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsMessage
     *
     * @param newsmessage the value for newsletter.newsMessage
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setNewsmessage(String newsmessage) {
        this.newsmessage = newsmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.publishTime
     *
     * @return the value of newsletter.publishTime
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.publishTime
     *
     * @param publishtime the value for newsletter.publishTime
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }
}