package com.example.studentsystem.entity;

public class NewsSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newssubject.subject
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newssubject.subject
     *
     * @return the value of newssubject.subject
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newssubject.subject
     *
     * @param subject the value for newssubject.subject
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }
}