package com.example.studentsystem.entity;

import java.util.Date;

public class NewsLetter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsID
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private Integer newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsName
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private String newsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.publisher
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.subject
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsMessage
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private String newsmessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.publishTime
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsletter.newsType
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    private Integer newstype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsID
     *
     * @return the value of newsletter.newsID
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsID
     *
     * @param newsid the value for newsletter.newsID
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsName
     *
     * @return the value of newsletter.newsName
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public String getNewsname() {
        return newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsName
     *
     * @param newsname the value for newsletter.newsName
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setNewsname(String newsname) {
        this.newsname = newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.publisher
     *
     * @return the value of newsletter.publisher
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.publisher
     *
     * @param publisher the value for newsletter.publisher
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.subject
     *
     * @return the value of newsletter.subject
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.subject
     *
     * @param subject the value for newsletter.subject
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsMessage
     *
     * @return the value of newsletter.newsMessage
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public String getNewsmessage() {
        return newsmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsMessage
     *
     * @param newsmessage the value for newsletter.newsMessage
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setNewsmessage(String newsmessage) {
        this.newsmessage = newsmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.publishTime
     *
     * @return the value of newsletter.publishTime
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.publishTime
     *
     * @param publishtime the value for newsletter.publishTime
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsletter.newsType
     *
     * @return the value of newsletter.newsType
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public Integer getNewstype() {
        return newstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsletter.newsType
     *
     * @param newstype the value for newsletter.newsType
     *
     * @mbggenerated Sun May 01 14:47:08 BST 2022
     */
    public void setNewstype(Integer newstype) {
        this.newstype = newstype;
    }
}