package com.example.studentsystem.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewsLetterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public NewsLetterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNewsidIsNull() {
            addCriterion("newsID is null");
            return (Criteria) this;
        }

        public Criteria andNewsidIsNotNull() {
            addCriterion("newsID is not null");
            return (Criteria) this;
        }

        public Criteria andNewsidEqualTo(Integer value) {
            addCriterion("newsID =", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidNotEqualTo(Integer value) {
            addCriterion("newsID <>", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidGreaterThan(Integer value) {
            addCriterion("newsID >", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("newsID >=", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidLessThan(Integer value) {
            addCriterion("newsID <", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidLessThanOrEqualTo(Integer value) {
            addCriterion("newsID <=", value, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidIn(List<Integer> values) {
            addCriterion("newsID in", values, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidNotIn(List<Integer> values) {
            addCriterion("newsID not in", values, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidBetween(Integer value1, Integer value2) {
            addCriterion("newsID between", value1, value2, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsidNotBetween(Integer value1, Integer value2) {
            addCriterion("newsID not between", value1, value2, "newsid");
            return (Criteria) this;
        }

        public Criteria andNewsnameIsNull() {
            addCriterion("newsName is null");
            return (Criteria) this;
        }

        public Criteria andNewsnameIsNotNull() {
            addCriterion("newsName is not null");
            return (Criteria) this;
        }

        public Criteria andNewsnameEqualTo(String value) {
            addCriterion("newsName =", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameNotEqualTo(String value) {
            addCriterion("newsName <>", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameGreaterThan(String value) {
            addCriterion("newsName >", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameGreaterThanOrEqualTo(String value) {
            addCriterion("newsName >=", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameLessThan(String value) {
            addCriterion("newsName <", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameLessThanOrEqualTo(String value) {
            addCriterion("newsName <=", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameLike(String value) {
            addCriterion("newsName like", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameNotLike(String value) {
            addCriterion("newsName not like", value, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameIn(List<String> values) {
            addCriterion("newsName in", values, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameNotIn(List<String> values) {
            addCriterion("newsName not in", values, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameBetween(String value1, String value2) {
            addCriterion("newsName between", value1, value2, "newsname");
            return (Criteria) this;
        }

        public Criteria andNewsnameNotBetween(String value1, String value2) {
            addCriterion("newsName not between", value1, value2, "newsname");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNull() {
            addCriterion("publisher is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNotNull() {
            addCriterion("publisher is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherEqualTo(String value) {
            addCriterion("publisher =", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotEqualTo(String value) {
            addCriterion("publisher <>", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThan(String value) {
            addCriterion("publisher >", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("publisher >=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThan(String value) {
            addCriterion("publisher <", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThanOrEqualTo(String value) {
            addCriterion("publisher <=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLike(String value) {
            addCriterion("publisher like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotLike(String value) {
            addCriterion("publisher not like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherIn(List<String> values) {
            addCriterion("publisher in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotIn(List<String> values) {
            addCriterion("publisher not in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherBetween(String value1, String value2) {
            addCriterion("publisher between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotBetween(String value1, String value2) {
            addCriterion("publisher not between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andNewsmessageIsNull() {
            addCriterion("newsMessage is null");
            return (Criteria) this;
        }

        public Criteria andNewsmessageIsNotNull() {
            addCriterion("newsMessage is not null");
            return (Criteria) this;
        }

        public Criteria andNewsmessageEqualTo(String value) {
            addCriterion("newsMessage =", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageNotEqualTo(String value) {
            addCriterion("newsMessage <>", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageGreaterThan(String value) {
            addCriterion("newsMessage >", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageGreaterThanOrEqualTo(String value) {
            addCriterion("newsMessage >=", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageLessThan(String value) {
            addCriterion("newsMessage <", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageLessThanOrEqualTo(String value) {
            addCriterion("newsMessage <=", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageLike(String value) {
            addCriterion("newsMessage like", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageNotLike(String value) {
            addCriterion("newsMessage not like", value, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageIn(List<String> values) {
            addCriterion("newsMessage in", values, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageNotIn(List<String> values) {
            addCriterion("newsMessage not in", values, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageBetween(String value1, String value2) {
            addCriterion("newsMessage between", value1, value2, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andNewsmessageNotBetween(String value1, String value2) {
            addCriterion("newsMessage not between", value1, value2, "newsmessage");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNull() {
            addCriterion("publishTime is null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNotNull() {
            addCriterion("publishTime is not null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeEqualTo(Date value) {
            addCriterion("publishTime =", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotEqualTo(Date value) {
            addCriterion("publishTime <>", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThan(Date value) {
            addCriterion("publishTime >", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publishTime >=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThan(Date value) {
            addCriterion("publishTime <", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThanOrEqualTo(Date value) {
            addCriterion("publishTime <=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIn(List<Date> values) {
            addCriterion("publishTime in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotIn(List<Date> values) {
            addCriterion("publishTime not in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeBetween(Date value1, Date value2) {
            addCriterion("publishTime between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotBetween(Date value1, Date value2) {
            addCriterion("publishTime not between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andNewstypeIsNull() {
            addCriterion("newsType is null");
            return (Criteria) this;
        }

        public Criteria andNewstypeIsNotNull() {
            addCriterion("newsType is not null");
            return (Criteria) this;
        }

        public Criteria andNewstypeEqualTo(Integer value) {
            addCriterion("newsType =", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeNotEqualTo(Integer value) {
            addCriterion("newsType <>", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeGreaterThan(Integer value) {
            addCriterion("newsType >", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("newsType >=", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeLessThan(Integer value) {
            addCriterion("newsType <", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeLessThanOrEqualTo(Integer value) {
            addCriterion("newsType <=", value, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeIn(List<Integer> values) {
            addCriterion("newsType in", values, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeNotIn(List<Integer> values) {
            addCriterion("newsType not in", values, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeBetween(Integer value1, Integer value2) {
            addCriterion("newsType between", value1, value2, "newstype");
            return (Criteria) this;
        }

        public Criteria andNewstypeNotBetween(Integer value1, Integer value2) {
            addCriterion("newsType not between", value1, value2, "newstype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsletter
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 28 22:32:24 BST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsletter
     *
     * @mbggenerated Thu Apr 28 22:32:24 BST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}