package com.example.studentsystem.entity;

public class SelectedCourse extends SelectedCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selectedcourse.mark
     *
     * @mbggenerated Sun Apr 24 21:11:13 BST 2022
     */
    private Integer mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selectedcourse.mark
     *
     * @return the value of selectedcourse.mark
     *
     * @mbggenerated Sun Apr 24 21:11:13 BST 2022
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selectedcourse.mark
     *
     * @param mark the value for selectedcourse.mark
     *
     * @mbggenerated Sun Apr 24 21:11:13 BST 2022
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }
}