package com.example.studentsystem.entity;

public class SubscribedSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribedsubject.subject
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribedsubject.studentID
     *
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    private Integer studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribedsubject.subject
     *
     * @return the value of subscribedsubject.subject
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribedsubject.subject
     *
     * @param subject the value for subscribedsubject.subject
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribedsubject.studentID
     *
     * @return the value of subscribedsubject.studentID
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribedsubject.studentID
     *
     * @param studentid the value for subscribedsubject.studentID
     * @mbggenerated Thu Apr 28 23:22:19 BST 2022
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
}