package com.example.studentsystem.entity;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacherID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.realName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.birthYear
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Date birthyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.degree
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.title
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.grade
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Date grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.collegeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer collegeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.majorID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    private Integer majorid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacherID
     *
     * @return the value of teacher.teacherID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacherID
     *
     * @param teacherid the value for teacher.teacherID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.realName
     *
     * @return the value of teacher.realName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.realName
     *
     * @param realname the value for teacher.realName
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.birthYear
     *
     * @return the value of teacher.birthYear
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Date getBirthyear() {
        return birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.birthYear
     *
     * @param birthyear the value for teacher.birthYear
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setBirthyear(Date birthyear) {
        this.birthyear = birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.degree
     *
     * @return the value of teacher.degree
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.degree
     *
     * @param degree the value for teacher.degree
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.title
     *
     * @return the value of teacher.title
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.title
     *
     * @param title the value for teacher.title
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.grade
     *
     * @return the value of teacher.grade
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Date getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.grade
     *
     * @param grade the value for teacher.grade
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setGrade(Date grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.collegeID
     *
     * @return the value of teacher.collegeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.collegeID
     *
     * @param collegeid the value for teacher.collegeID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.majorID
     *
     * @return the value of teacher.majorID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public Integer getMajorid() {
        return majorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.majorID
     *
     * @param majorid the value for teacher.majorID
     *
     * @mbggenerated Wed Apr 20 00:08:44 BST 2022
     */
    public void setMajorid(Integer majorid) {
        this.majorid = majorid;
    }
}