package com.example.studentsystem.entity;

public class TestTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testTable.testID
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    private Integer testid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testTable.testName
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    private String testname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testTable.testDesc
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    private String testdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testTable.testID
     *
     * @return the value of testTable.testID
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public Integer getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testTable.testID
     *
     * @param testid the value for testTable.testID
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public void setTestid(Integer testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testTable.testName
     *
     * @return the value of testTable.testName
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public String getTestname() {
        return testname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testTable.testName
     *
     * @param testname the value for testTable.testName
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public void setTestname(String testname) {
        this.testname = testname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testTable.testDesc
     *
     * @return the value of testTable.testDesc
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public String getTestdesc() {
        return testdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testTable.testDesc
     *
     * @param testdesc the value for testTable.testDesc
     *
     * @mbggenerated Mon Apr 18 23:45:05 BST 2022
     */
    public void setTestdesc(String testdesc) {
        this.testdesc = testdesc;
    }
}