package com.example.studentsystem.entity;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.userID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.userName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.password
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.role
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.userID
     *
     * @return the value of userlogin.userID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.userID
     *
     * @param userid the value for userlogin.userID
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.userName
     *
     * @return the value of userlogin.userName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.userName
     *
     * @param username the value for userlogin.userName
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.password
     *
     * @return the value of userlogin.password
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.password
     *
     * @param password the value for userlogin.password
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.role
     *
     * @return the value of userlogin.role
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.role
     *
     * @param role the value for userlogin.role
     *
     * @mbggenerated Wed Apr 20 11:34:33 BST 2022
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}